name: geocomp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - requests
  - tqdm
  - urllib
  - flask
  - h5py
  - matplotlib
  - scipy
  - numpy
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - ipyparallel
  - scikit-image
  - scikit-learn
  - sympy
  - pandas
  - pillow
  - pint
  - seaborn
  - bs4
  - zipfile
  - geopandas
  - shapely.geometry
  - cartopy
  - segysak
  - verde
  - xarray
  - python-ternary
  - pip:
    - bruges
    - welly
    - wellpathpy
    - segyio